# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.cfd01.com:
  peer0.aktex.cfd01.com:
  peer1.aktex.cfd01.com:
  peer0.insurex.cfd01.com:
  peer1.insurex.cfd01.com:
  peer0.shippex.cfd01.com:
  peer1.shippex.cfd01.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aktex
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.aktex.cfd01.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.aktex.cfd01.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/aktex.cfd01.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peeraktex
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurex
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurex.cfd01.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurex.cfd01.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/insurex.cfd01.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerinsurex
    networks:
      - byfn

  orderer.cfd01.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.cfd01.com
    container_name: orderer.cfd01.com
    networks:
      - byfn

  peer0.aktex.cfd01.com:
    container_name: peer0.aktex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.aktex.cfd01.com
    networks:
      - byfn

  peer1.aktex.cfd01.com:
    container_name: peer1.aktex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.aktex.cfd01.com
    networks:
      - byfn

  peer0.insurex.cfd01.com:
    container_name: peer0.insurex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurex.cfd01.com
    networks:
      - byfn

  peer1.insurex.cfd01.com:
    container_name: peer1.insurex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.insurex.cfd01.com
    networks:
      - byfn
  
  peer0.shippex.cfd01.com:
    container_name: peer0.shippex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.shippex.cfd01.com
    networks:
      - byfn

  peer1.insurex.cfd01.com:
    container_name: peer1.shippex.cfd01.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.shippex.cfd01.com
    networks:
      - byfn
