# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.cfd01.com:
    container_name: orderer.cfd01.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cfd01.com/orderers/orderer.cfd01.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cfd01.com/orderers/orderer.cfd01.com/tls/:/var/hyperledger/orderer/tls
    - orderer.cfd01.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.aktex.cfd01.com:
    container_name: peer0.aktex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.aktex.cfd01.com
      - CORE_PEER_ADDRESS=peer0.aktex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.aktex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.aktex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=aktexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/aktex.cfd01.com/peers/peer0.aktex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/aktex.cfd01.com/peers/peer0.aktex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer0.aktex.cfd01.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.aktex.cfd01.com:
    container_name: peer1.aktex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.aktex.cfd01.com
      - CORE_PEER_ADDRESS=peer1.aktex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.aktex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.aktex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=aktexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/aktex.cfd01.com/peers/peer1.aktex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/aktex.cfd01.com/peers/peer1.aktex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer1.aktex.cfd01.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.insurex.cfd01.com:
    container_name: peer0.insurex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurex.cfd01.com
      - CORE_PEER_ADDRESS=peer0.insurex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.insurex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=insurexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurex.cfd01.com/peers/peer0.insurex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurex.cfd01.com/peers/peer0.insurex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurex.cfd01.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.insurex.cfd01.com:
    container_name: peer1.insurex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.insurex.cfd01.com
      - CORE_PEER_ADDRESS=peer1.insurex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.insurex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=insurexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurex.cfd01.com/peers/peer1.insurex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurex.cfd01.com/peers/peer1.insurex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer1.insurex.cfd01.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.shippex.cfd01.com:
    container_name: peer0.shippex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shippex.cfd01.com
      - CORE_PEER_ADDRESS=peer0.shippex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shippex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.shippex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=shippexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shippex.cfd01.com/peers/peer0.shippex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shippex.cfd01.com/peers/peer0.shippex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer0.shippex.cfd01.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.shippex.cfd01.com:
    container_name: peer1.shippex.cfd01.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.shippex.cfd01.com
      - CORE_PEER_ADDRESS=peer1.shippex.cfd01.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.shippex.cfd01.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shippex.cfd01.com:7051
      - CORE_PEER_LOCALMSPID=shippexMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shippex.cfd01.com/peers/peer1.shippex.cfd01.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shippex.cfd01.com/peers/peer1.shippex.cfd01.com/tls:/etc/hyperledger/fabric/tls
        - peer1.shippex.cfd01.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
